name: Tag Release and deploy to k8s nonprod

permissions:
  id-token: write
  contents: write

concurrency:
  group: hello-k8s-${{ github.ref }}
  cancel-in-progress: true

env:
  ECR_REGISTRY: 560285300220.dkr.ecr.us-east-1.amazonaws.com/hello-k8s

on:
  push:
    tags:
      - 'v*'

jobs:
  tag-release:
    name: Validate tag, find image, tag image
    runs-on: arc-runners-bisnow
    steps:
      - uses: bisnow/github-actions-tag-release@devops/concurrency
        with:
          tag: ${{ github.ref_name }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}

  deploy-to-nonprod:
    uses: ./.github/workflows/deploy.yaml
    needs: tag-release
    with:
      tag: ${{ github.ref_name }}
      environment: nonprod
      manifest-path: .k8s/beta/hello-k8s-helmrelease.yaml
      skip-validation: true
    secrets: inherit
